### ISSUE TITLE
Attention is not compatible with `opencog-deps` and `ocpkg` cmake version

### ISSUE THREAD

**Issue by vsbogd** [opencog/attention#8]
`TARGET_LINK_DIRECTORIES` added into `CMakeLists.txt` by commit https://github.com/opencog/attention/commit/15c7faa94fe30b0ad0483548e72ddb2ec7933d7d is absent for CMake versions below 3.13. In particular it is incompatible with CMake 3.10 which is installed by `ocpkg` script in Ubuntu 18.04 and `opencog-deps` image.

**Comment by AmeBel** [comment]
https://github.com/opencog/ocpkg/pull/145 and https://github.com/opencog/docker/pull/145
fixes this. Cmake version is now 3.15.5
